"""Algorithm 1 of Section 3, and the AC stage of Section 3.4.

Every line of the pseudocode is tagged ``ALG1-Ln`` at the code implementing it.

    1  solve (M) with no risk cuts, obtain x0, cost z0, surrogate Phi0
    2  rho0 <- phi(x0),  k <- 0
    3  repeat
    4    k <- k + 1
    5    solve (S) at x^{k-1} to obtain A_k, the kappa components it selects
    6    append the cut family generated by A_k to (M)
    7    solve (M), obtain x^k, cost z^k, surrogate Phi^k
    8    rho^k <- phi(x^k),  Gamma^k <- (rho^k - Phi^k)/rho^k
    9  until rho^k/rho^0 <= 1 - eta or k = k-bar
    10 return (Pg^k, P^k, z^k, rho^k, Phi^k, Gamma^k)

The three stages:

    baseline  Algorithm 1 on (M); the reported dispatch is the DC one.
    a2        Algorithm 1 on (M), then (M^ac) solved ONCE with the pool the DC
              loop accumulated.  Section 3.4.
    a3        Algorithm 1 on (M^ac) throughout, separating on the AC dispatch.

The AC stage is one solve and there is no knob saying otherwise: Section 3.4 is
a transfer, not a re-separation, so `run_ac_stage` takes no iteration count.
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass, field
from typing import Callable, List, Optional

from . import risk
from .model import Master, Solution, SolverConfig
from .network import Network

STAGES = ("baseline", "a2", "a3")

DC_MODFILE = "master.mod"
AC_MODFILE = "master_ac.mod"

#: The weight grid of eq (weightgrid), as multiples of lambda*.  Geometric,
#: because the response to lambda is concentrated and not in the same place for
#: each representation.  By eq (weightstar) a multiple of lambda* is the ratio
#: xi/(tau_hi - tau_lo), so this runs from 1/4 to 4 units of nominal cost paid
#: per unit of nominal risk removed.
WEIGHT_GRID = (0.0, 0.25, 0.5, 1.0, 2.0, 4.0)

#: Significant digits the exchange rate is rounded to.  Without it, 0.05/0.2
#: is 0.25000000000000006 in binary and the same study written two ways would
#: not agree: on ACTIVSg200 that last digit moved the reported risk by 2.4e-6
#: relative, because where the master has many optima the barrier picks among
#: them on numerical detail alone.
RATE_SIGNIFICANT = 12


def exchange_rate(xi: float, tau_lo: float, tau_hi: float) -> float:
    """eq (weightstar): the multiplier xi/(tau_hi - tau_lo), so that
    lambda = exchange_rate(...) * lambda* with lambda* = z0/rho0.

    xi is a fraction of z0 and the band a fraction of rho0, so the rate is
    dimensionless and lambda takes its units from lambda* alone.  The band is
    NOT the eta of the termination test: eta is a target the loop exits on, the
    band is what the operator will pay, stated before the loop runs.
    """
    if xi < 0.0:
        raise ValueError(
            f"xi = {xi} is a cost tolerance as a fraction of z0 and cannot be "
            f"negative; a negative tolerance would price risk below zero")
    if not 0.0 < tau_lo < tau_hi <= 1.0:
        raise ValueError(
            f"the risk band must satisfy 0 < tau_lo < tau_hi <= 1, got "
            f"tau_lo = {tau_lo}, tau_hi = {tau_hi}. The band is a fraction of "
            f"rho0: tau_hi above 1 asks for more risk than the nominal "
            f"dispatch carries, and tau_lo >= tau_hi is an empty band whose "
            f"width would divide by zero or invert the price.")
    return _round_significant(xi / (tau_hi - tau_lo), RATE_SIGNIFICANT)


def _round_significant(value: float, digits: int) -> float:
    if value == 0.0 or not math.isfinite(value):
        return value
    return round(value, digits - 1 - int(math.floor(math.log10(abs(value)))))


def _noop(_message: str) -> None:
    return None


###############################################################################
# Inputs
###############################################################################


@dataclass
class AlgorithmConfig:
    """The Require line of Algorithm 1: phi, lambda, kappa, eta, k-bar.

    The weight is a multiple of lambda* = z0/rho0, which is not known until the
    nominal solve of line 1 has run.  `risk_weight` overrides it with an
    absolute value in $/p.u.
    """

    metric: str = "max_active_flow"
    stage: str = "baseline"
    #: The component set the active risk functional is maximized over,
    #: `risk.FLOW_DOMAINS`.
    flow_domain: str = "all"
    #: The grid point: lambda = weight_multiplier * lambda*.
    weight_multiplier: float = 1.0
    #: An absolute lambda, in $/p.u.  Set this only to bypass lambda*.
    risk_weight: Optional[float] = None
    #: kappa, the cut budget per iteration.
    kappa: int = 1
    #: eta, the target reduction in the functional.
    eta: float = 0.5
    #: k-bar, the iteration limit.
    k_bar: int = 25
    #: |Gamma| at which the surrogate has converged on the functional.
    #: Zero, the default, disables the test; eta and k-bar are then the only
    #: exits, as Algorithm 1 states them.
    gamma_tol: float = 0.0
    #: A component is reported as badly exposed at this fraction of rho^k.
    exposure_fraction: float = risk.EXPOSURE_FRACTION
    #: Write each master solve to this directory as ``master_k<k>.lp``.
    lp_dir: Optional[str] = None

    def __post_init__(self) -> None:
        if self.metric not in risk.METRICS:
            raise ValueError(f"unknown risk functional {self.metric!r}; "
                             f"expected one of {list(risk.METRICS)}")
        if self.stage not in STAGES:
            raise ValueError(f"unknown stage {self.stage!r}; "
                             f"expected one of {list(STAGES)}")
        if self.flow_domain not in risk.FLOW_DOMAINS:
            raise ValueError(f"unknown flow domain {self.flow_domain!r}; "
                             f"expected one of {list(risk.FLOW_DOMAINS)}")
        if self.kappa < 1:
            raise ValueError(f"kappa must be at least 1, got {self.kappa}")
        if not 0.0 < self.eta < 1.0:
            raise ValueError(
                f"eta is a fractional reduction and must lie in (0, 1), got "
                f"{self.eta}; eta = 0 exits before the loop runs and eta = 1 "
                f"asks the functional to reach zero")
        if self.k_bar < 1:
            raise ValueError(f"k-bar must be at least 1, got {self.k_bar}")
        if self.gamma_tol < 0.0:
            raise ValueError(
                f"gamma_tol is a tolerance on |Gamma| and cannot be negative, "
                f"got {self.gamma_tol}; 0 disables the test")
        if self.weight_multiplier < 0:
            raise ValueError("the risk weight cannot be negative")
        if self.risk_weight is not None and self.risk_weight < 0:
            raise ValueError("the risk weight cannot be negative")
        if not 0.0 < self.exposure_fraction <= 1.0:
            raise ValueError(f"the exposure fraction must lie in (0, 1], got "
                             f"{self.exposure_fraction}")

    @property
    def runs_on_ac(self) -> bool:
        """True when the cutting-plane loop itself solves (M^ac)."""
        return self.stage == "a3"

    @property
    def has_ac_stage(self) -> bool:
        """True when a single (M^ac) solve follows the loop.  Section 3.4."""
        return self.stage == "a2"


###############################################################################
# Outputs
###############################################################################


@dataclass
class Iterate:
    """One row of the trace: everything Algorithm 1 carries at iteration k."""

    k: int
    status: str
    #: z^k, the generation cost alone.  The objective carries lambda*Phi on top.
    cost: float
    #: Phi^k, the risk surrogate.
    surrogate: float
    #: rho^k = phi(x^k), the functional at this iterate.
    rho: float
    #: Gamma^k = (rho^k - Phi^k)/rho^k, the gap `gamma_tol` exits on.
    gamma: float
    #: rho^k/rho^0, the quantity the eta exit tests.
    ratio: float
    objective: float
    n_line_cuts: int
    n_bus_cuts: int
    cuts_added: int
    solve_time_s: float
    #: The badly exposed components at this iterate, worst first: branch counts
    #: for the line functionals, bus counts for the bus functional.
    exposed: List[int] = field(default_factory=list)
    #: Where this solve's LP was written, when LP output is on.
    lp_path: Optional[str] = None

    @property
    def solved(self) -> bool:
        return self.status == "solved"

    @property
    def n_exposed(self) -> int:
        return len(self.exposed)


@dataclass
class Result:
    """What one run of Algorithm 1 returns, plus what the study records."""

    case: str
    metric: str
    stage: str

    #: lambda* = z0/rho0, our eq (weightstar).
    lambda_star: float
    #: The lambda this run actually priced risk at.
    risk_weight: float
    weight_multiplier: Optional[float]

    #: The nominal quantities of lines 1-2, at lambda = 0 with no cuts.
    z0: float
    rho0: float
    phi0: float

    #: The component set eq (10a) was maximized over, carried beside `metric`
    #: because a rho is not comparable across domains.
    flow_domain: str = "all"

    iterations: List[Iterate] = field(default_factory=list)
    #: The single (M^ac) solve of Section 3.4.  Stage a2 only.
    ac: Optional[Iterate] = None

    #: Which exit was taken.  See `TERMINATIONS`.
    termination: str = "iteration_limit"
    termination_detail: str = ""

    #: The reported de-risked dispatch: the AC one where there is an AC stage.
    dispatch: Optional[Solution] = None
    #: The nominal dispatch of line 1, kept because the counterfactual ranks
    #: units on it once, at lambda = 0, and holds that ranking fixed.
    nominal_dispatch: Optional[Solution] = None

    total_time_s: float = 0.0
    config: Optional[AlgorithmConfig] = None

    @property
    def final(self) -> Iterate:
        """The iterate the loop exited on."""
        return self.iterations[-1]

    @property
    def reported(self) -> Iterate:
        """The iterate whose dispatch is reported: the AC one where there is one."""
        return self.ac if self.ac is not None else self.final

    @property
    def k_end(self) -> int:
        return self.final.k

    @property
    def n_cuts(self) -> int:
        return self.final.n_line_cuts + self.final.n_bus_cuts

    @property
    def risk_reduction(self) -> float:
        """1 - rho^end/rho^0 against THIS RUN'S OWN nominal solve, which on
        stage a2 is the DC one.  The frontier normalizes each stage against its
        own lambda = 0 row instead; see `ropf.results`."""
        return 1.0 - self.reported.ratio

    @property
    def cost_increase(self) -> float:
        """z^end/z^0 - 1 against this run's own nominal solve.  Same caveat."""
        if self.z0 == 0.0:
            return float("nan")
        return self.reported.cost / self.z0 - 1.0


#: Every way a run can stop.  A run that stops for a reason not in this list is
#: a bug, not a new outcome.
TERMINATIONS = (
    "eta_target",            # ALG1-L9, first exit: rho^k/rho^0 <= 1 - eta
    "iteration_limit",       # ALG1-L9, last exit: k = k-bar
    "zero_weight",           # lambda = 0; see run_loop
    "separation_exhausted",  # no component left to cut; Lemma 2.11
    "converged",             # ALG1-L9, second exit: |Gamma^k| <= gamma_tol
    "nominal_risk_zero",     # rho0 = 0, so lambda* and the ratio are undefined
    "infeasible",            # a master did not solve
)


###############################################################################
# Algorithm 1
###############################################################################


def run(network: Network,
        config: AlgorithmConfig,
        solver: Optional[SolverConfig] = None,
        ac_solver: Optional[SolverConfig] = None,
        log: Optional[Callable[[str], None]] = None) -> Result:
    """Run one stage end to end and return its `Result`.

    `solver` drives the cutting-plane loop and `ac_solver` the Section 3.4 AC
    solve; on stage a3 the loop is itself on (M^ac), so `ac_solver` drives it
    and `solver` is unused.
    """
    emit = log or _noop
    started = time.time()

    loop_solver = (ac_solver or SolverConfig(name="knitro")) \
        if config.runs_on_ac else (solver or SolverConfig())
    modfile = AC_MODFILE if config.runs_on_ac else DC_MODFILE

    emit(f"\nstage {config.stage}: {config.metric}, "
         f"lambda = {config.weight_multiplier:g} lambda*, "
         f"kappa = {config.kappa}, eta = {config.eta:g}, "
         f"k-bar = {config.k_bar}\n")

    # kappa cuts an iteration for at most k-bar iterations, so the pool cannot
    # exceed kappa * k-bar however the run goes.
    budget = config.kappa * config.k_bar
    master = Master(network, modfile, loop_solver, emit,
                    line_cut_capacity=budget, bus_cut_capacity=budget)
    if config.lp_dir:
        master.set_lp_output(config.lp_dir)

    result = run_loop(network, master, config, emit)

    if config.has_ac_stage and result.termination != "infeasible":
        run_ac_stage(network, master, result, config,
                     ac_solver or SolverConfig(name="knitro"), emit)

    result.total_time_s = time.time() - started
    emit(f" run finished in {result.total_time_s:.1f}s: {result.termination}"
         f" ({result.termination_detail})\n")
    return result


def run_loop(network: Network,
             master: Master,
             config: AlgorithmConfig,
             log: Optional[Callable[[str], None]] = None) -> Result:
    """Algorithm 1 on `master`, which is already loaded with `network`."""
    emit = log or _noop
    metric = config.metric
    master.set_risk_family(metric)

    # ---- ALG1-L1: (M) with no risk cuts, at lambda = 0 ---------------------
    # The nominal quantities are defined at lambda = 0, so the weight is zeroed
    # for this solve whatever the run's own lambda is.
    emit("\n ALG1-L1  nominal solve: lambda = 0, no cuts\n")
    master.set_risk_weight(0.0)
    master.lp_iteration = 0
    nominal = master.solve()

    result = Result(
        case=network.casefile or "?",
        metric=metric,
        stage=config.stage,
        flow_domain=config.flow_domain,
        lambda_star=float("nan"),
        risk_weight=float("nan"),
        weight_multiplier=(None if config.risk_weight is not None
                           else config.weight_multiplier),
        z0=nominal.gen_cost,
        rho0=float("nan"),
        phi0=nominal.phi,
        nominal_dispatch=nominal,
        dispatch=nominal,
        config=config,
    )

    if not nominal.solved:
        result.termination = "infeasible"
        result.termination_detail = f"nominal solve returned {nominal.status!r}"
        result.iterations.append(_iterate(0, nominal, float("nan"), float("nan"),
                                          master, 0))
        emit(f" the nominal solve did not solve: {nominal.status!r}\n")
        return result

    # ---- ALG1-L2: rho0 <- phi(x0), k <- 0 ----------------------------------
    ev = risk.evaluate(metric, network, nominal.Pf, config.flow_domain)
    rho0 = ev.value
    result.rho0 = rho0
    result.iterations.append(
        _iterate(0, nominal, rho0, rho0, master, 0, ev, config))
    emit(f" ALG1-L2  z0 = {result.z0:.6f} $, rho0 = {rho0:.6f} p.u.\n")
    _report_exposure(ev, config, network, nominal.Pf, emit)

    if rho0 <= 0.0:
        # lambda* = z0/rho0 and the exit test are both undefined.  A degenerate
        # case, not a converged one, and recorded as such.
        result.lambda_star = float("nan")
        result.risk_weight = 0.0
        result.termination = "nominal_risk_zero"
        result.termination_detail = (
            f"the functional is {rho0:g} at the nominal dispatch, so "
            f"lambda* = z0/rho0 and the ratio rho^k/rho^0 are undefined")
        emit(f" {result.termination_detail}\n")
        return result

    # ---- eq (weightstar): lambda* = z0/rho0 --------------------------------
    result.lambda_star = result.z0 / rho0
    risk_weight = (float(config.risk_weight) if config.risk_weight is not None
                   else config.weight_multiplier * result.lambda_star)
    result.risk_weight = risk_weight
    emit(f" lambda* = z0/rho0 = {result.lambda_star:.6f} $/p.u.;"
         f" this run prices risk at lambda = {risk_weight:.6f} $/p.u.\n")

    if risk_weight == 0.0:
        # Phi enters the objective at price lambda and the cuts bound it from
        # below only, so at lambda = 0 it is free: no cut can change the
        # dispatch and every iteration would return x0 until k-bar.
        result.termination = "zero_weight"
        result.termination_detail = (
            "lambda = 0, so the cut pool cannot change the dispatch and the "
            "nominal solve is the answer")
        emit(f" {result.termination_detail}\n")
        return result

    master.set_risk_weight(risk_weight)
    incumbent_ev = ev

    # ---- ALG1-L3: repeat ---------------------------------------------------
    for k in range(1, config.k_bar + 1):          # ALG1-L4: k <- k + 1
        # ---- ALG1-L5: separate at x^{k-1} ----------------------------------
        selected = risk.select(
            incumbent_ev, config.kappa,
            existing=(master.bus_cut_keys if incumbent_ev.is_bus_family
                      else set(master.line_cut_ids)))

        # ---- ALG1-L6: append the cut family --------------------------------
        if incumbent_ev.is_bus_family:
            added = master.add_bus_cuts(
                risk.build_bus_cuts(incumbent_ev, selected))
        else:
            added = master.add_line_cuts(selected)

        if added == 0:
            # Every component of positive contribution already carries its cut:
            # the finite termination of the greedy kernel (Lemma 2.11).
            result.termination = "separation_exhausted"
            result.termination_detail = (
                f"no new cut at k = {k}: every component the separation would "
                f"choose already carries one")
            emit(f" ALG1-L5  {result.termination_detail}\n")
            break

        # ---- ALG1-L7: solve (M) --------------------------------------------
        emit(f"\n ALG1-L7  k = {k}, pool {master.n_line_cuts} line cuts +"
             f" {master.n_bus_cuts} bus cuts (+{added} this iteration)\n")
        master.lp_iteration = k
        solution = master.solve()

        if not solution.solved:
            result.termination = "infeasible"
            result.termination_detail = (
                f"the master returned {solution.status!r} at k = {k}")
            result.iterations.append(
                _iterate(k, solution, float("nan"), rho0, master, added))
            emit(f" {result.termination_detail}\n")
            break

        # ---- ALG1-L8: rho^k, Gamma^k ---------------------------------------
        ev_k = risk.evaluate(metric, network, solution.Pf, config.flow_domain)
        iterate = _iterate(k, solution, ev_k.value, rho0, master, added,
                           ev_k, config)
        result.iterations.append(iterate)
        result.dispatch = solution
        incumbent_ev = ev_k

        emit(f" ALG1-L8  rho^{k} = {iterate.rho:.6f}, Phi^{k} = "
             f"{iterate.surrogate:.6f}, Gamma^{k} = {iterate.gamma:.6f}, "
             f"rho^{k}/rho^0 = {iterate.ratio:.6f}\n")
        _report_exposure(ev_k, config, network, solution.Pf, emit)

        # ---- ALG1-L9: until rho^k/rho^0 <= 1 - eta, |Gamma^k| <= gamma_tol,
        #      or k = k-bar ---------------------------------------------------
        if iterate.ratio <= 1.0 - config.eta:
            result.termination = "eta_target"
            result.termination_detail = (
                f"rho^{k}/rho^0 = {iterate.ratio:.6f} <= 1 - eta = "
                f"{1.0 - config.eta:.6f}")
            emit(f" ALG1-L9  {result.termination_detail}\n")
            break
        # After the eta target, so a run meeting both records the target it
        # was asked for; the two stop at the same k on the same dispatch.
        if config.gamma_tol > 0.0 and abs(iterate.gamma) <= config.gamma_tol:
            result.termination = "converged"
            result.termination_detail = (
                f"Gamma^{k} = {iterate.gamma:.3e} <= gamma_tol = "
                f"{config.gamma_tol:g} with rho^k/rho^0 = {iterate.ratio:.6f} "
                f"against the target {1.0 - config.eta:.6f}")
            emit(f" ALG1-L9  {result.termination_detail}\n")
            break
        if k == config.k_bar:
            result.termination = "iteration_limit"
            result.termination_detail = (
                f"k = k-bar = {config.k_bar} with rho^k/rho^0 = "
                f"{iterate.ratio:.6f}, above the target {1.0 - config.eta:.6f}")
            emit(f" ALG1-L9  {result.termination_detail}\n")
            break

    return result


def run_ac_stage(network: Network,
                 dc_master: Master,
                 result: Result,
                 config: AlgorithmConfig,
                 solver: SolverConfig,
                 log: Optional[Callable[[str], None]] = None) -> Iterate:
    """Section 3.4: append the DC pool to (M^ac) and solve it ONCE.

    The cuts are appended exactly as the DC loop accumulated them -- nothing is
    separated again here, which is what makes the hybrid a hand-off.

    THIS RUNS EVEN WHEN THE POOL IS EMPTY, which is the lambda = 0 grid point:
    (M^ac) with no cuts is the plain AC-OPF, and that is the nominal AC
    dispatch the stage's frontier needs.  Skipping it would leave a2 reporting
    a DC dispatch at lambda = 0 and AC ones elsewhere, so the difference across
    grid points would no longer be attributable to lambda alone.
    """
    emit = log or _noop

    n_line, n_bus = dc_master.n_line_cuts, dc_master.n_bus_cuts
    emit(f"\n Section 3.4  transferring {n_line} line + {n_bus} bus cuts"
         f" to (M^ac), which is solved once\n")

    ac = Master(network, AC_MODFILE, solver, emit,
                line_cut_capacity=max(1, n_line),
                bus_cut_capacity=max(1, n_bus))
    ac.set_risk_family(config.metric)
    ac.set_risk_weight(result.risk_weight)
    ac.add_line_cuts(dc_master.line_cut_ids)
    ac.add_bus_cuts(dc_master.bus_cuts)

    solution = ac.solve()
    ev = risk.evaluate(config.metric, network, solution.Pf, config.flow_domain)
    iterate = _iterate(result.k_end, solution, ev.value, result.rho0, ac, 0,
                       ev, config)
    result.ac = iterate

    if solution.solved:
        result.dispatch = solution
        emit(f" Section 3.4  AC dispatch: z = {iterate.cost:.6f} $, "
             f"rho = {iterate.rho:.6f} p.u., Gamma = {iterate.gamma:.6f}\n")
        _report_exposure(ev, config, network, solution.Pf, emit)
    else:
        # The DC result stands as the run's outcome; the AC iterate records
        # what happened rather than being discarded.
        result.termination_detail += \
            f"; the AC solve returned {solution.status!r}"
        emit(f" Section 3.4  the AC solve returned {solution.status!r};"
             f" the DC dispatch is reported\n")
    return iterate


###############################################################################
# Bookkeeping
###############################################################################

#: How many exposed components the transcript names before summarizing.
EXPOSURE_REPORT_LIMIT = 10


def _report_exposure(ev, config: AlgorithmConfig, network: Network, Pf,
                     emit: Callable[[str], None]) -> None:
    """Name the components carrying too much exposure at this iterate.

    Two lists, because they answer different questions: the exposed set is
    relative to the active functional, and the overloaded set is absolute,
    against each branch's own rateA.
    """
    bad = risk.exposed(ev, config.exposure_fraction)
    if bad:
        noun = "bus" if ev.is_bus_family else "line"
        emit(f" exposed  {_count(bad, noun)} at or above "
             f"{config.exposure_fraction:g} of rho: {_list(bad)}\n")

    over = risk.overloaded(network, Pf)
    if over:
        emit(f" overload {_count(over, 'line')} at or above the rating: "
             f"{_list(over)}\n")


def _count(components: List[int], noun: str) -> str:
    """"1 line", "3 lines", "2 buses"."""
    if len(components) == 1:
        return f"1 {noun}"
    suffix = "es" if noun.endswith("s") else "s"
    return f"{len(components)} {noun}{suffix}"


def _list(components: List[int]) -> str:
    """The counts, worst first, truncated at `EXPOSURE_REPORT_LIMIT`."""
    shown = ", ".join(str(c) for c in components[:EXPOSURE_REPORT_LIMIT])
    if len(components) > EXPOSURE_REPORT_LIMIT:
        shown += f", +{len(components) - EXPOSURE_REPORT_LIMIT} more"
    return shown


def _iterate(k: int, solution: Solution, rho: float, rho0: float,
             master: Master, cuts_added: int,
             ev=None, config: Optional[AlgorithmConfig] = None) -> Iterate:
    """Assemble one trace row.  Gamma and the ratio are undefined at rho = 0."""
    fraction = config.exposure_fraction if config else risk.EXPOSURE_FRACTION
    return Iterate(k=k,
                   status=solution.status,
                   cost=solution.gen_cost,
                   surrogate=solution.phi,
                   rho=rho,
                   gamma=(rho - solution.phi) / rho if rho else float("nan"),
                   ratio=rho / rho0 if rho0 else float("nan"),
                   objective=solution.objective,
                   n_line_cuts=master.n_line_cuts,
                   n_bus_cuts=master.n_bus_cuts,
                   cuts_added=cuts_added,
                   solve_time_s=solution.solve_time_s,
                   exposed=(risk.exposed(ev, fraction) if ev is not None else []),
                   lp_path=solution.lp_path)
